import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from 'next-auth/react'

const Home = () => {
  const { data: session } = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>Home| Try Auth!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Home page| welcome here!</h1>
        <h3>This is Home...</h3>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit commodi
          laboriosam quasi doloremque, sequi beatae. Voluptates asperiores nisi
          maxime optio.
        </p>
      </main>

      <div className={styles.authWrap}>
        {session && (
          <>
            {' '}
            Signed in as {session.user.name} <br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
        )}
        {!session && (
          <>
            Not signed in <br />
            <button onClick={() => signIn()}>Sign in</button>
          </>
        )}
      </div>
    </div>
  )
}

export default Home
